GET http://localhost:5000/products

###
GET http://localhost:5000/products/4

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 3",
    "price": 1900
}

###
PATCH http://localhost:5000/products/4
Content-Type: application/json

{
    "name": "Product 3 updated",
    "price": 1900
}

###
DELETE http://localhost:5000/products/4